import type { SimpleExercise } from '@/lib/exercise-types';

export const defaultExercises: SimpleExercise[] = [
  // GYM - Weighted
  {
    id: 'bench-press',
    name: 'Bench Press',
    category: 'GYM',
    exerciseType: 'weighted',
    muscleGroups: ['Chest', 'Triceps', 'Shoulders'],
    equipment: ['Barbell', 'Bench'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'squat',
    name: 'Squat',
    category: 'GYM',
    exerciseType: 'weighted',
    muscleGroups: ['Quads', 'Glutes', 'Hamstrings'],
    equipment: ['Barbell', 'Squat Rack'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: 'GYM',
    exerciseType: 'weighted',
    muscleGroups: ['Back', 'Hamstrings', 'Glutes'],
    equipment: ['Barbell'],
    difficulty: 'Intermediate',
    isCustom: false,
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'GYM',
    exerciseType: 'weighted',
    muscleGroups: ['Shoulders', 'Triceps'],
    equipment: ['Barbell'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'GYM',
    exerciseType: 'weighted',
    muscleGroups: ['Back', 'Biceps'],
    equipment: ['Barbell'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    category: 'GYM',
    exerciseType: 'weighted',
    muscleGroups: ['Chest', 'Shoulders', 'Triceps'],
    equipment: ['Dumbbells', 'Bench'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'GYM',
    exerciseType: 'weighted',
    muscleGroups: ['Back', 'Biceps'],
    equipment: ['Cable', 'Machine'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'GYM',
    exerciseType: 'weighted',
    muscleGroups: ['Quads', 'Glutes'],
    equipment: ['Machine'],
    difficulty: 'Beginner',
    isCustom: false,
  },

  // Calisthenics - Bodyweight
  {
    id: 'pull-up',
    name: 'Pull Up',
    category: 'Calisthenics',
    exerciseType: 'bodyweight',
    muscleGroups: ['Back', 'Biceps'],
    equipment: ['Pull-up Bar'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'negative-muscle-up',
    name: 'Negative Muscle Up',
    category: 'Calisthenics',
    exerciseType: 'bodyweight',
    muscleGroups: ['Back', 'Chest', 'Triceps'],
    equipment: ['Pull-up Bar', 'Rings'],
    difficulty: 'Intermediate',
    isCustom: false,
  },
  {
    id: 'muscle-up',
    name: 'Muscle Up',
    category: 'Calisthenics',
    exerciseType: 'bodyweight',
    muscleGroups: ['Back', 'Chest', 'Triceps'],
    equipment: ['Pull-up Bar', 'Rings'],
    difficulty: 'Advanced',
    isCustom: false,
  },
  {
    id: 'dips',
    name: 'Dips',
    category: 'Calisthenics',
    exerciseType: 'bodyweight',
    muscleGroups: ['Chest', 'Triceps', 'Shoulders'],
    equipment: ['Dip Station', 'Parallel Bars'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'push-up',
    name: 'Push Up',
    category: 'Calisthenics',
    exerciseType: 'bodyweight',
    muscleGroups: ['Chest', 'Triceps', 'Shoulders'],
    equipment: ['Bodyweight Only'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'chin-up',
    name: 'Chin Up',
    category: 'Calisthenics',
    exerciseType: 'bodyweight',
    muscleGroups: ['Back', 'Biceps'],
    equipment: ['Pull-up Bar'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push Up',
    category: 'Calisthenics',
    exerciseType: 'bodyweight',
    muscleGroups: ['Shoulders', 'Triceps'],
    equipment: ['Bodyweight Only'],
    difficulty: 'Intermediate',
    isCustom: false,
  },

  // Yoga / Stretching - Timed
  {
    id: 'downward-dog-hold',
    name: 'Downward Dog Hold',
    category: 'Yoga',
    exerciseType: 'timed',
    muscleGroups: ['Full Body'],
    equipment: ['Bodyweight Only'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'warrior-i-hold',
    name: 'Warrior I Hold',
    category: 'Yoga',
    exerciseType: 'timed',
    muscleGroups: ['Quads', 'Core'],
    equipment: ['Bodyweight Only'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'plank-hold',
    name: 'Plank Hold',
    category: 'Yoga',
    exerciseType: 'timed',
    muscleGroups: ['Core'],
    equipment: ['Bodyweight Only'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'l-sit-hold',
    name: 'L-Sit Hold',
    category: 'Calisthenics',
    exerciseType: 'timed',
    muscleGroups: ['Core', 'Triceps'],
    equipment: ['Parallel Bars', 'Bodyweight Only'],
    difficulty: 'Intermediate',
    isCustom: false,
  },
  {
    id: 'dead-hang',
    name: 'Dead Hang',
    category: 'Calisthenics',
    exerciseType: 'timed',
    muscleGroups: ['Forearms', 'Back'],
    equipment: ['Pull-up Bar'],
    difficulty: 'Beginner',
    isCustom: false,
  },

  // Cardio
  {
    id: 'running',
    name: 'Running',
    category: 'Cardio',
    exerciseType: 'timed',
    muscleGroups: ['Quads', 'Hamstrings', 'Calves'],
    equipment: ['Bodyweight Only'],
    difficulty: 'Beginner',
    isCustom: false,
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    category: 'Cardio',
    exerciseType: 'timed',
    muscleGroups: ['Calves', 'Full Body'],
    equipment: ['Bodyweight Only'],
    difficulty: 'Beginner',
    isCustom: false,
  },
];
