export type LanguageMode = "english" | "vietnamese";

const EN_TO_VI_MAP: Record<string, string> = {
  "Settings": "Cài đặt",
  "Configure your training interface": "Tùy chỉnh giao diện tập luyện",
  "Settings Summary": "Tổng quan cài đặt",
  "User:": "Người dùng:",
  "Theme:": "Giao diện:",
  "Date Format:": "Định dạng ngày:",
  "Terminology:": "Thuật ngữ:",
  "Language:": "Ngôn ngữ:",
  "Exercise Foreign Language:": "Tên ngoại ngữ bài tập:",
  "Weight Unit:": "Đơn vị cân nặng:",
  "Variation Labels:": "Nhãn biến thể:",
  "Date Format": "Định dạng ngày",
  "Terminology": "Thuật ngữ",
  "Weight Unit": "Đơn vị cân nặng",
  "Variation Labels": "Nhãn biến thể",
  "Actions": "Hành động",
  "Cultivation": "Tu luyện",
  "Conventional": "Thông dụng",
  "Wuxia-themed labels": "Nhãn theo phong cách võ hiệp",
  "Standard fitness labels": "Nhãn tập luyện tiêu chuẩn",
  "Kilograms (kg)": "Kilogram (kg)",
  "Pounds (lbs)": "Pound (lbs)",
  "Abbreviated": "Viết tắt",
  "Short labels": "Nhãn ngắn",
  "Full Text": "Đầy đủ",
  "Expanded labels": "Nhãn đầy đủ",
  "Reset Display Settings": "Đặt lại cài đặt hiển thị",
  "Logout": "Đăng xuất",
  "English": "Tiếng Anh",
  "Vietnamese": "Tiếng Việt",
  "Language Learning Hint": "Gợi ý học ngôn ngữ",
  "Exercise Language": "Ngôn ngữ bài tập",
  "Show Foreign Name": "Hiện tên ngoại ngữ",
  "Hide Foreign Name": "Ẩn tên ngoại ngữ",
  "Display opposite exercise name in parentheses": "Hiển thị tên bài tập đối ngôn ngữ trong ngoặc",
  "Only show primary exercise name": "Chỉ hiển thị tên bài tập chính",
  "Enabled": "Bật",
  "Disabled": "Tắt",

  "Path of Cultivation": "Con đường tu luyện",
  "Enter the realm of cultivation": "Tiến vào giới tu luyện",
  "Welcome back, cultivator": "Chào mừng bạn trở lại",
  "Enter your cultivator name": "Nhập tên tu luyện",
  "Your display name": "Tên hiển thị của bạn",
  "Enter your secret art": "Nhập mật khẩu",
  "Remember Me": "Ghi nhớ đăng nhập",
  "Hide password": "Ẩn mật khẩu",
  "Show password": "Hiện mật khẩu",
  "Channeling Qi...": "Đang xử lý...",
  "Begin Cultivation": "Bắt đầu",
  "Enter the Sect": "Vào hệ thống",
  "Already a cultivator?": "Đã có tài khoản?",
  "Return to the sect": "Quay lại đăng nhập",
  "New cultivator?": "Người mới?",
  "Join the sect": "Đăng ký",
  "Heaven rewards the diligent": "Trời không phụ người có công",
  "Cannot connect to server/database. Please verify the server URL and your network connection.": "Không thể kết nối máy chủ/cơ sở dữ liệu. Vui lòng kiểm tra URL máy chủ và kết nối mạng của bạn.",
  "An error occurred": "Đã xảy ra lỗi",

  "Dao Name": "Tên đăng nhập",
  "True Name": "Tên thật",
  "Secret Art": "Mật khẩu",

  "Overview": "Tổng quan",
  "Navigation Hub": "Trung tâm điều hướng",
  "Check-In": "Điểm danh",
  "Workouts": "Bài tập",
  "Rank Up": "Thăng hạng",
  "Completionist": "Hoàn thành tất cả",
  "Train": "Tập luyện",
  "Friends": "Bạn bè",
  "Exercise Library": "Thư viện bài tập",
  "Attendance": "Điểm danh",
  "Progress": "Tiến độ",
  "Workout History": "Lịch sử tập luyện",
  "Community Feed": "Bảng tin cộng đồng",
  "Admin Panel": "Bảng quản trị",
  "Progressions": "Lộ trình",
  "Immortal’s Log": "Nhật ký bất tử",
  "Navigation": "Điều hướng",
  "Admin": "Quản trị",
  "More": "Thêm",
  "Sign Out": "Đăng xuất",
  "Website Information": "Thông tin trang web",
  "Body Profile": "Hồ sơ cơ thể",
  "Update Weight & Gender": "Cập nhật cân nặng và giới tính",
  "Pages": "Trang",
  "Account": "Tài khoản",
  "Quick access to your pages and profile": "Truy cập nhanh đến các trang và hồ sơ của bạn",
  "Keep your stats current for accurate training targets.": "Giữ thông số luôn cập nhật để mục tiêu tập luyện chính xác hơn.",
  "Home": "Trang chủ",
  "Training": "Tập luyện",
  "Theme": "Giao diện",
  "Date": "Ngày",
  "Date:": "Ngày:",
  "All": "Tất cả",
  "Today": "Hôm nay",
  "Jan": "Th1",
  "Feb": "Th2",
  "Mar": "Th3",
  "Apr": "Th4",
  "May": "Th5",
  "Jun": "Th6",
  "Jul": "Th7",
  "Aug": "Th8",
  "Sep": "Th9",
  "Oct": "Th10",
  "Nov": "Th11",
  "Dec": "Th12",
  "Category": "Danh mục",
  "Exercise": "Bài tập",
  "Exercise Name": "Tên bài tập",
  "Progression": "Lộ trình",
  "Variant": "Biến thể",
  "Notes": "Ghi chú",
  "Training Log": "Nhật ký tập luyện",
  "Training Log Input": "Nhập nhật ký tập luyện",
  "Training Log Input Section": "Khu vực nhập nhật ký tập luyện",
  "Simple view": "Chế độ đơn giản",
  "Simple View": "Chế độ đơn giản",
  "Open": "Mở",
  "Edit": "Sửa",
  "Edit training log": "Sửa nhật ký tập luyện",
  "Edit Training Log": "Sửa nhật ký tập luyện",
  "Reset": "Đặt lại",
  "Reset Headers": "Đặt lại tiêu đề",
  "Save": "Lưu",
  "Cancel": "Hủy",
  "Add": "Thêm",
  "Saving...": "Đang lưu...",
  "Deleting...": "Đang xóa...",
  "No logs yet": "Chưa có bản ghi",
  "No training data logged yet.": "Chưa có dữ liệu tập luyện nào được ghi.",
  "No training data logged yet. Select an exercise from the sidebar to log your first set.": "Chưa có dữ liệu tập luyện nào được ghi. Hãy chọn một bài tập từ thanh bên để ghi bộ đầu tiên.",
  "Select a row to edit": "Chọn một hàng để chỉnh sửa",
  "Full-page table": "Bảng toàn trang",
  "Fit-to-screen table": "Bảng vừa màn hình",
  "Weight": "Tạ",
  "Timed": "Theo thời gian",
  "Existing Exercise": "Bài tập hiện có",
  "Add New Exercise": "Thêm bài tập mới",
  "Collapsed": "Thu gọn",
  "Input is disabled while viewing another user.": "Không thể nhập khi đang xem người dùng khác.",
  "Mode": "Chế độ",
  "Unit": "Đơn vị",
  "Mod": "Điều chỉnh",
  "Modifier": "Điều chỉnh",
  "Clear": "Xóa",
  "Clear exercise search": "Xóa tìm kiếm bài tập",
  "Open training log input": "Mở phần nhập nhật ký tập luyện",
  "Delete Training Record": "Xóa bản ghi tập luyện",
  "Delete Record": "Xóa bản ghi",
  "Are you sure you want to permanently delete the log record for": "Bạn có chắc muốn xóa vĩnh viễn bản ghi cho",
  "cannot be undone.": "Hành động này không thể hoàn tác.",
  "Exercise History": "Lịch sử bài tập",
  "Select an exercise in Training Log Input": "Chọn một bài tập trong phần Nhập nhật ký tập luyện",
  "Open full history": "Mở toàn bộ lịch sử",
  "Minimize exercise history": "Thu nhỏ lịch sử bài tập",
  "Minimize": "Thu nhỏ",
  "Collapse exercise history": "Thu gọn lịch sử bài tập",
  "Expand exercise history": "Mở rộng lịch sử bài tập",
  "Collapse": "Thu gọn",
  "Expand": "Mở rộng",
  "Close exercise history": "Đóng lịch sử bài tập",
  "Choose an exercise from the input section to view its history.": "Chọn một bài tập từ phần nhập để xem lịch sử.",
  "Loading history...": "Đang tải lịch sử...",
  "Loading...": "Đang tải...",
  "No history found for this exercise yet.": "Chưa có lịch sử cho bài tập này.",
  "Average Weight": "Trung bình tạ",
  "Average Reps": "Trung bình reps",
  "Avg W": "TB Tạ",
  "Avg R": "TB Reps",
  "Var": "Biến thể",
  "Loading more...": "Đang tải thêm...",
  "Load more history": "Tải thêm lịch sử",
  "History": "Lịch sử",
  "No exercises found": "Không tìm thấy bài tập",
  "Training logs updated successfully!": "Cập nhật nhật ký tập luyện thành công!",
  "Failed to save changes": "Không thể lưu thay đổi",
  "Network error — unable to save changes": "Lỗi mạng — không thể lưu thay đổi",
  "Log record deleted successfully": "Xóa bản ghi thành công",
  "Failed to delete record": "Không thể xóa bản ghi",
  "Network error — unable to delete record": "Lỗi mạng — không thể xóa bản ghi",
  "Add notes...": "Thêm ghi chú...",
  "Delete this log record": "Xóa bản ghi này",
  "Change Progression Tier": "Đổi tầng lộ trình",
  "Training History": "Lịch sử tập luyện",
  "No training sessions recorded for this technique yet.": "Chưa có buổi tập nào được ghi cho bài này.",
  "Hold": "Giữ",
  "Clear search": "Xóa tìm kiếm",
  "Sort": "Sắp xếp",
  "Custom order": "Thứ tự tùy chỉnh",
  "Most recent": "Mới nhất",
  "Most popular": "Phổ biến nhất",
  "The path of cultivation is long": "Con đường tu luyện còn dài",
  "Drag to reorder": "Kéo để sắp xếp lại",
  "Simple progression overview for calisthenics skills": "Tổng quan lộ trình đơn giản cho các kỹ năng calisthenics",
  "Skills": "Kỹ năng",
  "Sessions": "Phiên",
  "Active (14d)": "Hoạt động (14 ngày)",
  "Filters": "Bộ lọc",
  "Search skill...": "Tìm kỹ năng...",
  "All Skills": "Tất cả kỹ năng",
  "Active (7 days)": "Hoạt động (7 ngày)",
  "Active (14 days)": "Hoạt động (14 ngày)",
  "Active (30 days)": "Hoạt động (30 ngày)",
  "Stale (30+ days ago)": "Cũ (hơn 30 ngày trước)",
  "Never Attempted": "Chưa từng thử",
  "Sort: Recently trained": "Sắp xếp: Tập gần đây",
  "Sort: Most sessions": "Sắp xếp: Nhiều phiên nhất",
  "Sort: Least sessions": "Sắp xếp: Ít phiên nhất",
  "Sort: Most tiers": "Sắp xếp: Nhiều tầng nhất",
  "Sort: Name (A-Z)": "Sắp xếp: Tên (A-Z)",
  "Showing: Attempted Exercises": "Hiển thị: Bài tập đã thử",
  "Show Attempted Exercises Only": "Chỉ hiển thị bài tập đã thử",
  "Loading rank-up data...": "Đang tải dữ liệu thăng hạng...",
  "No skills found for the current filters.": "Không tìm thấy kỹ năng phù hợp với bộ lọc hiện tại.",
  "Hide Charts": "Ẩn biểu đồ",
  "Show Charts": "Hiện biểu đồ",
  "Show:": "Hiện:",
  "Just Me": "Chỉ mình tôi",
  "Monthly Comparison": "So sánh theo tháng",
  "Check-in rate %": "Tỷ lệ điểm danh %",
  "Weight Trend": "Xu hướng cân nặng",
  "No weight data recorded": "Chưa có dữ liệu cân nặng",
  "Avg:": "Trung bình:",
  "My Cultivation View": "Góc nhìn tu luyện của tôi",
  "Full-width table": "Bảng toàn chiều rộng",
  "In": "Điểm danh",
  "Not In": "Chưa điểm danh",
  "Weight:": "Cân nặng:",
  "No entries for this view": "Không có bản ghi cho chế độ xem này",
  "Use the calendar above to check in and add notes": "Dùng lịch ở trên để điểm danh và thêm ghi chú",
  "Open this day": "Mở ngày này",
  "Mine": "Của tôi",
  "Statistics": "Thống kê",
  "Check-in Rate": "Tỷ lệ điểm danh",
  "Days Checked In": "Số ngày đã điểm danh",
  "Best Streak": "Chuỗi tốt nhất",
  "All-time": "Toàn thời gian",
  "No data yet": "Chưa có dữ liệu",
  "days": "ngày",

  "Midnight Ink": "Mực đêm",
  "Deep void + jade accents": "Nền tối sâu với điểm nhấn ngọc",
  "Mountain Mist": "Sương núi",
  "Ink wash + mist": "Mực loang và sương mờ",
  "Calligraphy": "Thư pháp",
  "Monochrome scroll style": "Phong cách cuộn giấy đơn sắc",
  "Sakura": "Sakura",
  "Light blossom palette": "Bảng màu hoa anh đào sáng",
  "Sakura Dark": "Sakura tối",
  "Deep rose dusk": "Hoàng hôn hồng đậm",
  "Eternal": "Vĩnh hằng",
  "Clean minimalist": "Tối giản tinh gọn",
  "Discord": "Discord",
  "Discord-inspired dark": "Tông tối lấy cảm hứng từ Discord",
  "Document": "Tài liệu",
  "Paper + slate": "Giấy và đá phiến",
  "Nyaa": "Nyaa",
  "Nyaa blue-green": "Xanh lam ngọc Nyaa",
  "UI in English": "Giao diện bằng tiếng Anh",
  "UI in Vietnamese": "Giao diện bằng tiếng Việt",
  "User Settings": "Cài đặt người dùng",
  "Open user physique settings": "Mở cài đặt thể trạng người dùng",
  "Used to auto-select gym progression tier from average set weight vs bodyweight percentage.": "Dùng để tự động chọn tầng lộ trình gym từ trung bình tạ mỗi set so với phần trăm cân nặng cơ thể.",
  "Gender": "Giới tính",
  "Male": "Nam",
  "Female": "Nữ",
  "Gender affects weight standard calculations for your tier": "Giới tính ảnh hưởng đến việc tính chuẩn tạ cho tầng của bạn",
  "Bodyweight (kg)": "Cân nặng cơ thể (kg)",
  "Sync with Check-In Weight": "Đồng bộ với cân nặng điểm danh",
  "Automatically updated from check-ins": "Tự động cập nhật từ điểm danh",
  "Loading check-in data...": "Đang tải dữ liệu điểm danh...",
  "e.g. 82.5": "ví dụ: 82.5",
  "Use Last Known Weight": "Dùng cân nặng gần nhất",
  "Last check-in:": "Điểm danh gần nhất:",
  "No check-in weight records found": "Không tìm thấy bản ghi cân nặng điểm danh",
  "Failed to load check-in data": "Không thể tải dữ liệu điểm danh",
  "Loading feed...": "Đang tải bảng tin...",
  "Circle": "Vòng kết",
  "Your cultivation circle": "Vòng kết tu luyện của bạn",
  "Nothing yet": "Chưa có gì",
  "When your circle logs workouts, their sessions will appear here.": "Khi vòng bạn bè ghi buổi tập, các phiên sẽ hiện ở đây.",
  "Unknown": "Không rõ",
  "Open friend drawer": "Mở bảng thông tin bạn bè",
  "Collapse sets": "Thu gọn các set",
  "Expand sets": "Mở rộng các set",
  "Set values": "Giá trị set",
  "Incoming": "Yêu cầu đến",
  "Outgoing": "Yêu cầu đi",
  "Active": "Đang hoạt động",
  "Theme unknown": "Không rõ giao diện",
  "Last check-in": "Lần điểm danh gần nhất",
  "Member since": "Thành viên từ",
  "Last activity": "Hoạt động gần nhất",
  "Remove": "Gỡ",
  "this friend": "người bạn này",
  "No sets recorded": "Chưa có set nào được ghi",
  "Enter a friend code first.": "Hãy nhập mã bạn bè trước.",
  "Request sent.": "Đã gửi yêu cầu.",
  "Failed to send request.": "Không thể gửi yêu cầu.",
  "Loading members...": "Đang tải thành viên...",
  "Add by friend code": "Thêm bằng mã bạn bè",
  "Friend code": "Mã bạn bè",
  "Your code:": "Mã của bạn:",
  "No activity": "Chưa có hoạt động",
  "Loading requests...": "Đang tải yêu cầu...",
  "No pending requests": "Không có yêu cầu chờ",
  "No outgoing requests": "Không có yêu cầu đã gửi",
  "Accept": "Chấp nhận",
  "Decline": "Từ chối",
  "No added weight": "Không thêm tạ",
  "No resistance band": "Không dây kháng lực",
  "No variation": "Không biến thể",
  "Session notes, cues, or pain markers...": "Ghi chú buổi tập, chỉ dẫn hoặc dấu hiệu đau...",
  "Notes...": "Ghi chú...",
  "Loading more rows...": "Đang tải thêm hàng...",
  "Scroll for more": "Cuộn để xem thêm",
  "Loading more activity...": "Đang tải thêm hoạt động...",
  "No more activity": "Không còn hoạt động nào",
  "Load more activity": "Tải thêm hoạt động",
  "Feed": "Bảng tin",
  "Members": "Thành viên",
  "Requests": "Yêu cầu",
  "Status:": "Trạng thái:",
  "Completed": "Hoàn thành",
  "Logged": "Đã ghi",
  "Sets:": "Số set:",
  "Volume:": "Khối lượng:",
  "User created successfully.": "Tạo người dùng thành công.",
  "Failed to create user.": "Không thể tạo người dùng.",
  "Send this user to the recycle bin? Their active records will be removed from the app until restored.": "Chuyển người dùng này vào thùng rác? Dữ liệu hoạt động của họ sẽ bị gỡ khỏi ứng dụng cho đến khi khôi phục.",
  "User moved to the recycle bin.": "Đã chuyển người dùng vào thùng rác.",
  "Failed to move user to the recycle bin.": "Không thể chuyển người dùng vào thùng rác.",
  "Display name updated.": "Đã cập nhật tên hiển thị.",
  "Failed to update display name.": "Không thể cập nhật tên hiển thị.",
  "Password and confirmation do not match.": "Mật khẩu và xác nhận mật khẩu không khớp.",
  "Your password was updated. Use the new password on your next sign-in.": "Mật khẩu của bạn đã được cập nhật. Hãy dùng mật khẩu mới ở lần đăng nhập tiếp theo.",
  "Password updated. Share the new credentials securely.": "Mật khẩu đã được cập nhật. Hãy chia sẻ thông tin đăng nhập mới một cách an toàn.",
  "Failed to update password.": "Không thể cập nhật mật khẩu.",
  "You cannot remove your own admin privileges.": "Bạn không thể tự gỡ quyền quản trị của chính mình.",
  "Account type updated to": "Đã cập nhật loại tài khoản thành",
  "Failed to update account type.": "Không thể cập nhật loại tài khoản.",
  "Select a user before exporting.": "Hãy chọn người dùng trước khi xuất.",
  "Preparing backup package...": "Đang chuẩn bị gói sao lưu...",
  "Export failed": "Xuất thất bại",
  "Select a user before importing.": "Hãy chọn người dùng trước khi nhập.",
  "Reading backup file...": "Đang đọc tệp sao lưu...",
  "Import failed": "Nhập thất bại",
  "Select a user before purging.": "Hãy chọn người dùng trước khi xóa dữ liệu.",
  "Purging user backup data...": "Đang xóa dữ liệu sao lưu người dùng...",
  "Purge failed": "Xóa dữ liệu thất bại",
  "Preparing exercise library export...": "Đang chuẩn bị xuất thư viện bài tập...",
  "Exercise library export failed": "Xuất thư viện bài tập thất bại",
  "Reading exercise library file...": "Đang đọc tệp thư viện bài tập...",
  "Exercise library import failed": "Nhập thư viện bài tập thất bại",
  "Purge the shared Application Exercise Library? This clears the deployed library canvas and preserves user history for later restore.": "Xóa toàn bộ Thư viện Bài tập Ứng dụng dùng chung? Hành động này sẽ dọn trống thư viện đang triển khai và giữ lại lịch sử người dùng để khôi phục sau.",
  "Purging Application Exercise Library...": "Đang xóa Thư viện Bài tập Ứng dụng...",
  "Exercise DB purge failed": "Xóa Exercise DB thất bại",
  // Dashboard home
  "Good morning": "Chào buổi sáng",
  "Good afternoon": "Chào buổi chiều",
  "Good evening": "Chào buổi tối",
  "Checked in": "Đã điểm danh",
  "Not checked in": "Chưa điểm danh",
  "Check-in": "Điểm danh",
  "Cultivation Path": "Con đường tu luyện",
  "Day": "Ngày",
  "Start workout": "Bắt đầu tập luyện",
  "Open your training log and begin today's session": "Mở nhật ký tập luyện và bắt đầu buổi hôm nay",
  "Your stats": "Thống kê của bạn",
  "Profile & preferences": "Hồ sơ & tùy chọn",
  "Trend": "Xu hướng",
  "Check-ins": "Số lần điểm danh",
  "all time": "tổng cộng",
  "Streak": "Chuỗi liên tiếp",
  "keep it alive": "giữ vững nhé",
  "start today": "bắt đầu hôm nay",
  "latest check-in": "lần gần nhất",
  "This week": "Tuần này",
  "Last week": "Tuần trước",
  "Your week": "Tuần của bạn",
  "since last check-in": "kể từ lần gần nhất",
  "day": "ngày",
  "Previous week": "Tuần trước",
  "Next week": "Tuần tiếp theo",
  // Check-in page
  "Daily check-in and notes": "Điểm danh hàng ngày và ghi chú",
  "Friend": "Bạn",
  "Circle members": "Thành viên vòng kết",
  "Open friend actions": "Mở thao tác bạn bè",
  "Back from friend drawer": "Quay lại từ bảng bạn bè",
  "Your Friend": "Bạn của bạn",
  "Friend Overview": "Tổng quan bạn bè",
  "No check-in": "Chưa điểm danh",
  "Back to friend drawer": "Quay lại bảng bạn bè",
  "Back to friend history": "Quay lại lịch sử bạn bè",
  "Open exercise search": "Mở tìm kiếm bài tập",
  "Close exercise search": "Đóng tìm kiếm bài tập",
  "Open exercise filters": "Mở bộ lọc bài tập",
  "Exercise Filters": "Bộ lọc bài tập",
  "Clear filters": "Xóa bộ lọc",
  "No exercises logged yet.": "Chưa có bài tập nào được ghi.",
  "Last History": "Lịch sử gần nhất",
  "Last Chart": "Biểu đồ gần nhất",
  "Last Check-In": "Điểm danh gần nhất",
  "Last Chat": "Trò chuyện gần nhất",
  "Last Activity": "Hoạt động gần nhất",
  "Last workout": "Buổi tập gần nhất",
  "No workout history yet": "Chưa có lịch sử buổi tập",
  "Uses workout data from": "Sử dụng dữ liệu buổi tập từ",
  "No chart data yet": "Chưa có dữ liệu biểu đồ",
  "No check-ins yet": "Chưa có lần điểm danh nào",
  "Last seen": "Lần thấy gần nhất",
  "Coming soon": "Sắp ra mắt",
  "This now opens as a dedicated drawer instead of switching the page.": "Mục này giờ mở trong bảng riêng thay vì chuyển trang.",
  "Upcoming notes": "Ghi chú sắp tới",
  "Jump to this date": "Nhảy đến ngày này",
  "Me": "Tôi",
  "You": "Bạn",
  "Close": "Đóng",
  "Note": "Ghi chú",
  "Save Note": "Lưu ghi chú",
  "Circle today": "Vòng kết hôm nay",
  "Circle on": "Vòng kết ngày",
  "Weight (kg)": "Cân nặng (kg)",
  "Last:": "Gần nhất:",
  "Check-in is automatic when you log a workout.": "Điểm danh tự động khi bạn ghi nhật ký tập luyện.",
  "Add a short note for this day": "Thêm ghi chú ngắn cho ngày này",
  "Future days only support a personal note. Full check-in is available on the day itself.": "Ngày tương lai chỉ hỗ trợ ghi chú cá nhân. Điểm danh đầy đủ chỉ khả dụng vào ngày đó.",
  "⚖️ Log Your Weight": "⚖️ Ghi nhận cân nặng",
  "You haven't logged your weight for this check-in. Tracking your weight helps monitor your cultivation progress.": "Bạn chưa ghi cân nặng cho lần điểm danh này. Theo dõi cân nặng giúp kiểm soát tiến trình tu luyện.",
  "Body Weight (kg)": "Cân nặng cơ thể (kg)",
  "Enter your weight...": "Nhập cân nặng...",
  "⚖️ Save with Weight": "⚖️ Lưu với cân nặng",
  "Skip for Now": "Bỏ qua lúc này",
  "Hide 1 Hour": "Ẩn 1 giờ",
  "Don't remind me today": "Không nhắc nhở hôm nay",
  // Check-in modals and feed
  "View": "Xem",
  "How would you like to open this day?": "Bạn muốn mở ngày này như thế nào?",
  "No recorded check-in for this day.": "Không có dữ liệu điểm danh cho ngày này.",
  "Entry details": "Chi tiết điểm danh",
  "Weight recorded": "Đã ghi cân nặng",
  "No weight": "Chưa có cân nặng",
  "Note recorded": "Đã có ghi chú",
  "No note": "Chưa có ghi chú",
  "Rest day": "Ngày nghỉ",
  "Rest": "Nghỉ",
  "Check-in history": "Lịch sử điểm danh",
  "Start checking in to build your history timeline": "Bắt đầu điểm danh để xây dựng lịch sử của bạn",
  // Train history and workout detail
  "Already saved today": "Đã lưu hôm nay",
  "Saved": "Đã lưu",
  "Unable to save": "Không thể lưu",
  "Review your training logs and cultivation entries": "Xem lại nhật ký tập luyện và ghi chép tu luyện của bạn",
  "Back to my train history": "Quay lại lịch sử tập của tôi",
  "Search exercises": "Tìm bài tập",
  "Open filters": "Mở bộ lọc",
  "No exercises match your search.": "Không có bài tập nào khớp với tìm kiếm của bạn.",
  "coming soon": "sắp ra mắt",
  "UI placeholder ready. Functionality will be added in the next step.": "Khung giao diện đã sẵn sàng. Tính năng sẽ được bổ sung ở bước tiếp theo.",
  "Close day overview": "Đóng tổng quan ngày tập",
  "Manage Training Days": "Quản lý ngày tập",
  "Manage day allocations": "Quản lý phân bổ ngày",
  "Assign exercises to specific training days.": "Gán bài tập vào các ngày tập cụ thể.",
  "Show empty days": "Hiển thị ngày trống",
  "Toggle on to show days without assigned exercises in the day rail.": "Bật để hiển thị các ngày chưa có bài tập trên thanh ngày.",
  "Toggle empty day visibility": "Chuyển hiển thị ngày trống",
  "Close day exercises": "Đóng danh sách bài tập theo ngày",
  "No exercises assigned to": "Không có bài tập nào được gán cho",
  "Close exercise filters": "Đóng bộ lọc bài tập",
  "All categories": "Tất cả danh mục",
  "Sort by": "Sắp xếp theo",
  "Relevant": "Liên quan",
  "Recent first": "Mới nhất trước",
  "Oldest first": "Cũ nhất trước",
  "Name A-Z": "Tên A-Z",
  "Updated": "Cập nhật",
  "Last 7 days": "7 ngày gần đây",
  "Last 30 days": "30 ngày gần đây",
  "New Workout Log": "Nhật ký buổi tập mới",
  "Close workout logger chooser": "Đóng bộ chọn ghi buổi tập",
  "Filter by category": "Lọc theo danh mục",
  "Sort exercises": "Sắp xếp bài tập",
  "New Custom Exercise": "Bài tập tùy chỉnh mới",
  "Create a new exercise name and send it to review.": "Tạo tên bài tập mới và gửi để xét duyệt.",
  "No exercises match your search or filters.": "Không có bài tập nào khớp với tìm kiếm hoặc bộ lọc.",
  "No exercises match the current filters.": "Không có bài tập nào khớp với bộ lọc hiện tại.",
  "Progress overview": "Tổng quan tiến độ",
  "logged once": "đã ghi một lần",
  "Logged once": "Đã ghi một lần",
  "Untouched": "Chưa đụng đến",
  "Could not load progress data right now.": "Hiện không thể tải dữ liệu tiến độ.",
  "Toggle search": "Bật/tắt tìm kiếm",
  "Search exercise...": "Tìm bài tập...",
  "logs": "bản ghi",
  "coverage": "độ phủ",
  "Coverage": "Độ phủ",
  "tiers available": "tầng khả dụng",
  "no sessions logged yet": "chưa có buổi nào được ghi",
  "Last": "Lần gần nhất",
  "attempts": "lần thử",
  "Log session": "Ghi buổi",
  "Close filters": "Đóng bộ lọc",
  "Progress filters": "Bộ lọc tiến độ",
  "Filter": "Lọc",
  "Close filter drawer": "Đóng ngăn bộ lọc",
  "All exercises": "Tất cả bài tập",
  "Active in 14 days": "Hoạt động trong 14 ngày",
  "Stale 30+ days": "Cũ 30+ ngày",
  "Never logged": "Chưa từng ghi",
  "Showing logged exercises": "Đang hiển thị bài tập đã ghi",
  "Show logged only": "Chỉ hiển thị bài đã ghi",
  "Recently trained": "Tập gần đây",
  "Best coverage": "Độ phủ tốt nhất",
  "Most sessions": "Nhiều buổi nhất",
  "hold": "giữ",
  "Never": "Chưa từng",
  "Back to exercise list": "Quay lại danh sách bài tập",
  "Log a session for this exercise": "Ghi một buổi tập cho bài tập này",
  "Log a session": "Ghi buổi tập",
  "Close log search": "Đóng tìm kiếm bản ghi",
  "Open log search": "Mở tìm kiếm bản ghi",
  "Open log filters": "Mở bộ lọc bản ghi",
  "Search logs": "Tìm bản ghi",
  "Log Filters": "Bộ lọc bản ghi",
  "All progressions": "Tất cả tiến trình",
  "All variations": "Tất cả biến thể",
  "All loads": "Tất cả mức tạ",
  "Weighted": "Có tạ",
  "All rep ranges": "Tất cả khoảng reps",
  "1–5 reps": "1–5 reps",
  "6–10 reps": "6–10 reps",
  "11+ reps": "11+ reps",
  "Progression ascending": "Tiến trình tăng dần",
  "Progression descending": "Tiến trình giảm dần",
  "No workout history for this exercise yet.": "Chưa có lịch sử tập cho bài tập này.",
  "No logs match your search or filters.": "Không có bản ghi nào khớp với tìm kiếm hoặc bộ lọc.",
  "Loading latest check-in data...": "Đang tải dữ liệu điểm danh mới nhất...",
  "Quick Weight / Note": "Cân nặng / Ghi chú nhanh",
  "Close quick check-in drawer": "Đóng khung điểm danh nhanh",
  "Weight already recorded today": "Hôm nay đã ghi cân nặng",
  "How are you feeling today?": "Hôm nay bạn thấy thế nào?",
  "Note already recorded today": "Hôm nay đã ghi ghi chú",
  "Go to Check-In": "Đi tới Điểm danh",
  "Slide up for workout log or left for quick weight and note": "Vuốt lên để ghi buổi tập hoặc vuốt trái để ghi nhanh cân nặng và ghi chú",
  "Slide up: workout log, slide left: quick weight/note": "Vuốt lên: ghi buổi tập, vuốt trái: cân nặng/ghi chú nhanh",
  "Thank you!": "Cảm ơn!",
  "Log your weight!": "Ghi cân nặng của bạn!",
  "Assigned": "Được gán",
  "Completed today": "Hoàn thành hôm nay",
  "Recent": "Gần đây",
  "Back to Exercise Library": "Quay lại thư viện bài tập",
  "Back to History": "Quay lại lịch sử",
  "Back to Train": "Quay lại mục Tập luyện",
  "Compact training record for this workout": "Bản ghi tập luyện gọn cho bài tập này",
  "Loading workout history...": "Đang tải lịch sử tập...",
  "Workout not found.": "Không tìm thấy bài tập.",
  "You are currently viewing this user's filtered history for this exercise.": "Bạn đang xem lịch sử đã lọc của người dùng này cho bài tập này.",
  "Exercise snapshot": "Tóm tắt bài tập",
  "Current Progression": "Tiến trình hiện tại",
  "Unassigned progression": "Chưa gán tiến trình",
  "Last Logged": "Lần ghi gần nhất",
  "Total Logs": "Tổng bản ghi",
  "Completion": "Hoàn thành",
  "Difficulty / Equipment": "Độ khó / Dụng cụ",
  "Activity": "Hoạt động",
  "Primary Muscles": "Nhóm cơ chính",
  "Assigned Days": "Ngày được gán",
  "Filtered to progression": "Đang lọc theo tiến trình",
  "Level": "Cấp",
  "Other": "Khác",
  "Avg Weight": "Tạ trung bình",
  "Avg Reps": "Reps trung bình",
  "minute ago": "phút trước",
  "minutes ago": "phút trước",
  "hour ago": "giờ trước",
  "hours ago": "giờ trước",
  "day ago": "ngày trước",
  "days ago": "ngày trước",
  "e.g. 165": "ví dụ: 165",
  "e.g. 75": "ví dụ: 75",
  // Log workout editor
  "Failed to load this logged session.": "Không thể tải phiên đã ghi này.",
  "is not assigned to": "không được gán cho",
  "this day": "ngày này",
  "from": "khỏi",
  "Removed from": "Đã gỡ khỏi",
  "Failed to remove from day. Please try again.": "Không thể gỡ khỏi ngày. Vui lòng thử lại.",
  "Enter at least one set before saving.": "Hãy nhập ít nhất một set trước khi lưu.",
  "Enter a custom exercise name first.": "Hãy nhập tên bài tập tùy chỉnh trước.",
  "Select an exercise before saving.": "Hãy chọn bài tập trước khi lưu.",
  "Failed to": "Không thể",
  "update": "cập nhật",
  "save": "lưu",
  "training log": "nhật ký tập luyện",
  "Delete this logged session? This action cannot be undone.": "Xóa phiên đã ghi này? Hành động này không thể hoàn tác.",
  "Failed to delete this logged session.": "Không thể xóa phiên đã ghi này.",
  "We'll save this as a custom exercise so you can keep using it.": "Chúng tôi sẽ lưu đây là bài tập tùy chỉnh để bạn tiếp tục dùng.",
  "progression tiers": "tầng tiến trình",
  "Choose an exercise from the previous screen.": "Hãy chọn bài tập từ màn hình trước.",
  "time": "thời gian",
  "Custom exercise": "Bài tập tùy chỉnh",
  "No exercise selected": "Chưa chọn bài tập",
  "min": "phút",
  "sec": "giây",
  "Edit Workout": "Sửa buổi tập",
  "Log a Workout": "Ghi buổi tập",
  "Update or delete this workout.": "Cập nhật hoặc xóa buổi tập này.",
  "Track your sets and reps.": "Theo dõi các set và reps của bạn.",
  "Back to workout history": "Quay lại lịch sử buổi tập",
  "Back to train": "Quay lại mục tập luyện",
  "Removing...": "Đang gỡ...",
  "Remove from day": "Gỡ khỏi ngày",
  "Applying...": "Đang áp dụng...",
  "Apply Changes": "Áp dụng thay đổi",
  "Steps": "Các bước",
  "Reset session": "Đặt lại phiên",
  "Session date": "Ngày buổi tập",
  "Selected exercise": "Bài tập đã chọn",
  "Select a parent exercise": "Chọn bài tập gốc",
  "Custom exercise name": "Tên bài tập tùy chỉnh",
  "Type the exercise name you want": "Nhập tên bài tập bạn muốn",
  "Exercise setup": "Thiết lập bài tập",
  "— locked to assignment": "— khóa theo phân công",
  "Default": "Mặc định",
  "Session format": "Định dạng buổi tập",
  "Load and reps": "Mức tạ và reps",
  "Seconds and holds": "Giây và giữ",
  "Input unit": "Đơn vị nhập",
  "Seconds": "Giây",
  "Minutes": "Phút",
  "Kilograms": "Kilôgam",
  "Pounds": "Pao",
  "None": "Không có",
  "Weight modifier slider": "Thanh trượt điều chỉnh tạ",
  "Sets": "Các set",
  "Tap to continue this set": "Chạm để tiếp tục set này",
  "Add Set": "Thêm set",
  "Anything important from this session...": "Điều gì quan trọng từ buổi tập này...",
  "Working sets": "Set thực hiện",
  "No sets added yet.": "Chưa có set nào được thêm.",
  "Session notes": "Ghi chú buổi tập",
  "No notes added for this session.": "Chưa có ghi chú cho buổi tập này.",
  "reps": "reps",

  // ── Settings page ──────────────────────────────────────────
  "Appearance": "Diện mạo",
  "Theme style": "Kiểu giao diện",
  "Light": "Sáng",
  "Dark": "Tối",
  "Auto": "Tự động",
  "Calendar": "Lịch",
  "Date and region": "Ngày tháng & khu vực",
  "Timezone": "Múi giờ",
  "Date format": "Định dạng ngày",
  "Week starts on": "Tuần bắt đầu từ",
  "Language": "Ngôn ngữ",
  "Interface language": "Ngôn ngữ giao diện",
  "App language": "Ngôn ngữ ứng dụng",
  "Use English across the interface": "Sử dụng tiếng Anh cho giao diện",
  "Preview": "Xem trước",
  "Application interface": "Giao diện ứng dụng",
  "Units": "Đơn vị",
  "Preferred weight unit": "Đơn vị cân nặng ưa thích",
  "Best for metric-based training logs": "Phù hợp cho nhật ký hệ mét",
  "Best for imperial-based training logs": "Phù hợp cho nhật ký hệ Anh",
  "Bench Press": "Đẩy ngực",
  "Timed display unit": "Đơn vị hiển thị thời gian",
  "Seconds (s)": "Giây (s)",
  "e.g. 90s — raw seconds": "VD: 90 giây — giây thô",
  "Minutes (m s)": "Phút (p g)",
  "e.g. 1m 30s — easier to read": "VD: 1p 30g — dễ đọc hơn",
  "Plank": "Plank",
  "History defaults": "Mặc định lịch sử",
  "Default history view": "Chế độ xem mặc định",
  "Compact": "Thu gọn",
  "Dense rows for quick scanning": "Hàng thu gọn để xem nhanh",
  "Detailed": "Chi tiết",
  "Expanded row details": "Chi tiết hàng đầy đủ",
  "Default scope": "Phạm vi mặc định",
  "Your entries and your friends": "Lượt nhập của bạn và bạn bè",
  "Only your personal entries": "Chỉ lượt nhập cá nhân",
  "Only friends' entries": "Chỉ lượt nhập của bạn bè",
};

const VI_TO_EN_MAP: Record<string, string> = Object.fromEntries(
  Object.entries(EN_TO_VI_MAP).map(([en, vi]) => [vi, en]),
);

function normalizeLookupKey(text: string): string {
  return text.trim();
}

export function translateEnglishToLanguage(englishText: string, languageMode: LanguageMode): string {
  if (languageMode !== "vietnamese") {
    return englishText;
  }
  const key = normalizeLookupKey(englishText);
  return EN_TO_VI_MAP[key] ?? englishText;
}

export function getLearningHintFromEnglish(englishText: string, languageMode: LanguageMode): string | null {
  const key = normalizeLookupKey(englishText);
  if (!key) return null;
  const vietnamese = EN_TO_VI_MAP[key];

  if (languageMode === "vietnamese") {
    return vietnamese ? key : null;
  }

  return vietnamese && vietnamese !== key ? vietnamese : null;
}

export function translateLooseText(text: string, languageMode: LanguageMode): string {
  if (languageMode !== "vietnamese") {
    return text;
  }
  const key = normalizeLookupKey(text);
  return EN_TO_VI_MAP[key] ?? text;
}

export function reverseTranslateLooseText(text: string): string | null {
  const key = normalizeLookupKey(text);
  return VI_TO_EN_MAP[key] ?? null;
}

export function isSupportedLanguageMode(value: unknown): value is LanguageMode {
  return value === "english" || value === "vietnamese";
}
