export type LanguageMode = "english" | "vietnamese";

const EN_TO_VI_MAP: Record<string, string> = {
  "Settings": "Cài đặt",
  "Configure your training interface": "Tùy chỉnh giao diện tập luyện",
  "Settings Summary": "Tổng quan cài đặt",
  "User:": "Người dùng:",
  "Theme:": "Giao diện:",
  "Date Format:": "Định dạng ngày:",
  "Terminology:": "Thuật ngữ:",
  "Language:": "Ngôn ngữ:",
  "Exercise Foreign Language:": "Tên ngoại ngữ bài tập:",
  "Weight Unit:": "Đơn vị cân nặng:",
  "Variation Labels:": "Nhãn biến thể:",
  "Date Format": "Định dạng ngày",
  "Terminology": "Thuật ngữ",
  "Weight Unit": "Đơn vị cân nặng",
  "Variation Labels": "Nhãn biến thể",
  "Actions": "Hành động",
  "Cultivation": "Tu luyện",
  "Conventional": "Thông dụng",
  "Wuxia-themed labels": "Nhãn theo phong cách võ hiệp",
  "Standard fitness labels": "Nhãn tập luyện tiêu chuẩn",
  "Kilograms (kg)": "Kilogram (kg)",
  "Pounds (lbs)": "Pound (lbs)",
  "Abbreviated": "Viết tắt",
  "Short labels": "Nhãn ngắn",
  "Full Text": "Đầy đủ",
  "Expanded labels": "Nhãn đầy đủ",
  "Reset Display Settings": "Đặt lại cài đặt hiển thị",
  "Logout": "Đăng xuất",
  "English": "Tiếng Anh",
  "Vietnamese": "Tiếng Việt",
  "Language Learning Hint": "Gợi ý học ngôn ngữ",
  "Exercise Language": "Ngôn ngữ bài tập",
  "Show Foreign Name": "Hiện tên ngoại ngữ",
  "Hide Foreign Name": "Ẩn tên ngoại ngữ",
  "Display opposite exercise name in parentheses": "Hiển thị tên bài tập đối ngôn ngữ trong ngoặc",
  "Only show primary exercise name": "Chỉ hiển thị tên bài tập chính",
  "Enabled": "Bật",
  "Disabled": "Tắt",

  "Path of Cultivation": "Con đường tu luyện",
  "Enter the realm of cultivation": "Tiến vào giới tu luyện",
  "Welcome back, cultivator": "Chào mừng bạn trở lại",
  "Enter your cultivator name": "Nhập tên tu luyện",
  "Your display name": "Tên hiển thị của bạn",
  "Enter your secret art": "Nhập mật khẩu",
  "Remember Me": "Ghi nhớ đăng nhập",
  "Hide password": "Ẩn mật khẩu",
  "Show password": "Hiện mật khẩu",
  "Channeling Qi...": "Đang xử lý...",
  "Begin Cultivation": "Bắt đầu",
  "Enter the Sect": "Vào hệ thống",
  "Already a cultivator?": "Đã có tài khoản?",
  "Return to the sect": "Quay lại đăng nhập",
  "New cultivator?": "Người mới?",
  "Join the sect": "Đăng ký",
  "Heaven rewards the diligent": "Trời không phụ người có công",
  "Cannot connect to server/database. Please verify the server URL and your network connection.": "Không thể kết nối máy chủ/cơ sở dữ liệu. Vui lòng kiểm tra URL máy chủ và kết nối mạng của bạn.",
  "An error occurred": "Đã xảy ra lỗi",

  "Dao Name": "Tên đăng nhập",
  "True Name": "Tên thật",
  "Secret Art": "Mật khẩu",

  "Overview": "Tổng quan",
  "Navigation Hub": "Trung tâm điều hướng",
  "Check-In": "Điểm danh",
  "Workouts": "Bài tập",
  "Rank Up": "Thăng hạng",
  "Completionist": "Hoàn thành tất cả",
  "Train": "Tập luyện",
  "Friends": "Bạn bè",
  "Exercise Library": "Thư viện bài tập",
  "Attendance": "Điểm danh",
  "Progress": "Tiến độ",
  "Workout History": "Lịch sử tập luyện",
  "Community Feed": "Bảng tin cộng đồng",
  "Admin Panel": "Bảng quản trị",
  "Progressions": "Lộ trình",
  "Immortal’s Log": "Nhật ký bất tử",
  "Navigation": "Điều hướng",
  "Admin": "Quản trị",
  "More": "Thêm",
  "Sign Out": "Đăng xuất",
  "Website Information": "Thông tin trang web",
  "Body Profile": "Hồ sơ cơ thể",
  "Update Weight & Gender": "Cập nhật cân nặng và giới tính",
  "Pages": "Trang",
  "Account": "Tài khoản",
  "Quick access to your pages and profile": "Truy cập nhanh đến các trang và hồ sơ của bạn",
  "Keep your stats current for accurate training targets.": "Giữ thông số luôn cập nhật để mục tiêu tập luyện chính xác hơn.",
  "Home": "Trang chủ",
  "Training": "Tập luyện",
  "Theme": "Giao diện",
  "Date": "Ngày",
  "Date:": "Ngày:",
  "All": "Tất cả",
  "Today": "Hôm nay",
  "Jan": "Th1",
  "Feb": "Th2",
  "Mar": "Th3",
  "Apr": "Th4",
  "May": "Th5",
  "Jun": "Th6",
  "Jul": "Th7",
  "Aug": "Th8",
  "Sep": "Th9",
  "Oct": "Th10",
  "Nov": "Th11",
  "Dec": "Th12",
  "Category": "Danh mục",
  "Exercise": "Bài tập",
  "Exercise Name": "Tên bài tập",
  "Progression": "Lộ trình",
  "Variant": "Biến thể",
  "Notes": "Ghi chú",
  "Training Log": "Nhật ký tập luyện",
  "Training Log Input": "Nhập nhật ký tập luyện",
  "Training Log Input Section": "Khu vực nhập nhật ký tập luyện",
  "Simple view": "Chế độ đơn giản",
  "Simple View": "Chế độ đơn giản",
  "Open": "Mở",
  "Edit": "Sửa",
  "Edit training log": "Sửa nhật ký tập luyện",
  "Edit Training Log": "Sửa nhật ký tập luyện",
  "Reset": "Đặt lại",
  "Reset Headers": "Đặt lại tiêu đề",
  "Save": "Lưu",
  "Cancel": "Hủy",
  "Add": "Thêm",
  "Saving...": "Đang lưu...",
  "Deleting...": "Đang xóa...",
  "No logs yet": "Chưa có bản ghi",
  "No training data logged yet.": "Chưa có dữ liệu tập luyện nào được ghi.",
  "No training data logged yet. Select an exercise from the sidebar to log your first set.": "Chưa có dữ liệu tập luyện nào được ghi. Hãy chọn một bài tập từ thanh bên để ghi bộ đầu tiên.",
  "Select a row to edit": "Chọn một hàng để chỉnh sửa",
  "Full-page table": "Bảng toàn trang",
  "Fit-to-screen table": "Bảng vừa màn hình",
  "Weight": "Tạ",
  "Timed": "Theo thời gian",
  "Existing Exercise": "Bài tập hiện có",
  "Add New Exercise": "Thêm bài tập mới",
  "Collapsed": "Thu gọn",
  "Input is disabled while viewing another user.": "Không thể nhập khi đang xem người dùng khác.",
  "Mode": "Chế độ",
  "Unit": "Đơn vị",
  "Mod": "Điều chỉnh",
  "Modifier": "Điều chỉnh",
  "Clear": "Xóa",
  "Clear exercise search": "Xóa tìm kiếm bài tập",
  "Open training log input": "Mở phần nhập nhật ký tập luyện",
  "Delete Training Record": "Xóa bản ghi tập luyện",
  "Delete Record": "Xóa bản ghi",
  "Are you sure you want to permanently delete the log record for": "Bạn có chắc muốn xóa vĩnh viễn bản ghi cho",
  "cannot be undone.": "Hành động này không thể hoàn tác.",
  "Exercise History": "Lịch sử bài tập",
  "Select an exercise in Training Log Input": "Chọn một bài tập trong phần Nhập nhật ký tập luyện",
  "Open full history": "Mở toàn bộ lịch sử",
  "Minimize exercise history": "Thu nhỏ lịch sử bài tập",
  "Minimize": "Thu nhỏ",
  "Collapse exercise history": "Thu gọn lịch sử bài tập",
  "Expand exercise history": "Mở rộng lịch sử bài tập",
  "Collapse": "Thu gọn",
  "Expand": "Mở rộng",
  "Close exercise history": "Đóng lịch sử bài tập",
  "Choose an exercise from the input section to view its history.": "Chọn một bài tập từ phần nhập để xem lịch sử.",
  "Loading history...": "Đang tải lịch sử...",
  "Loading...": "Đang tải...",
  "No history found for this exercise yet.": "Chưa có lịch sử cho bài tập này.",
  "Average Weight": "Trung bình tạ",
  "Average Reps": "Trung bình reps",
  "Avg W": "TB Tạ",
  "Avg R": "TB Reps",
  "Var": "Biến thể",
  "Loading more...": "Đang tải thêm...",
  "Load more history": "Tải thêm lịch sử",
  "History": "Lịch sử",
  "No exercises found": "Không tìm thấy bài tập",
  "Training logs updated successfully!": "Cập nhật nhật ký tập luyện thành công!",
  "Failed to save changes": "Không thể lưu thay đổi",
  "Network error — unable to save changes": "Lỗi mạng — không thể lưu thay đổi",
  "Log record deleted successfully": "Xóa bản ghi thành công",
  "Failed to delete record": "Không thể xóa bản ghi",
  "Network error — unable to delete record": "Lỗi mạng — không thể xóa bản ghi",
  "Add notes...": "Thêm ghi chú...",
  "Delete this log record": "Xóa bản ghi này",
  "Change Progression Tier": "Đổi tầng lộ trình",
  "Training History": "Lịch sử tập luyện",
  "No training sessions recorded for this technique yet.": "Chưa có buổi tập nào được ghi cho bài này.",
  "Hold": "Giữ",
  "Clear search": "Xóa tìm kiếm",
  "Sort": "Sắp xếp",
  "Custom order": "Thứ tự tùy chỉnh",
  "Most recent": "Mới nhất",
  "Most popular": "Phổ biến nhất",
  "The path of cultivation is long": "Con đường tu luyện còn dài",
  "Drag to reorder": "Kéo để sắp xếp lại",
  "Simple progression overview for calisthenics skills": "Tổng quan lộ trình đơn giản cho các kỹ năng calisthenics",
  "Skills": "Kỹ năng",
  "Sessions": "Phiên",
  "Active (14d)": "Hoạt động (14 ngày)",
  "Filters": "Bộ lọc",
  "Search skill...": "Tìm kỹ năng...",
  "All Skills": "Tất cả kỹ năng",
  "Active (7 days)": "Hoạt động (7 ngày)",
  "Active (14 days)": "Hoạt động (14 ngày)",
  "Active (30 days)": "Hoạt động (30 ngày)",
  "Stale (30+ days ago)": "Cũ (hơn 30 ngày trước)",
  "Never Attempted": "Chưa từng thử",
  "Sort: Recently trained": "Sắp xếp: Tập gần đây",
  "Sort: Most sessions": "Sắp xếp: Nhiều phiên nhất",
  "Sort: Least sessions": "Sắp xếp: Ít phiên nhất",
  "Sort: Most tiers": "Sắp xếp: Nhiều tầng nhất",
  "Sort: Name (A-Z)": "Sắp xếp: Tên (A-Z)",
  "Showing: Attempted Exercises": "Hiển thị: Bài tập đã thử",
  "Show Attempted Exercises Only": "Chỉ hiển thị bài tập đã thử",
  "Loading rank-up data...": "Đang tải dữ liệu thăng hạng...",
  "No skills found for the current filters.": "Không tìm thấy kỹ năng phù hợp với bộ lọc hiện tại.",
  "Hide Charts": "Ẩn biểu đồ",
  "Show Charts": "Hiện biểu đồ",
  "Show:": "Hiện:",
  "Just Me": "Chỉ mình tôi",
  "Monthly Comparison": "So sánh theo tháng",
  "Check-in rate %": "Tỷ lệ điểm danh %",
  "Weight Trend": "Xu hướng cân nặng",
  "No weight data recorded": "Chưa có dữ liệu cân nặng",
  "Avg:": "Trung bình:",
  "My Cultivation View": "Góc nhìn tu luyện của tôi",
  "Full-width table": "Bảng toàn chiều rộng",
  "In": "Điểm danh",
  "Not In": "Chưa điểm danh",
  "Weight:": "Cân nặng:",
  "No entries for this view": "Không có bản ghi cho chế độ xem này",
  "Use the calendar above to check in and add notes": "Dùng lịch ở trên để điểm danh và thêm ghi chú",
  "Open this day": "Mở ngày này",
  "Mine": "Của tôi",
  "Statistics": "Thống kê",
  "Check-in Rate": "Tỷ lệ điểm danh",
  "Days Checked In": "Số ngày đã điểm danh",
  "Best Streak": "Chuỗi tốt nhất",
  "All-time": "Toàn thời gian",
  "No data yet": "Chưa có dữ liệu",
  "days": "ngày",

  "Midnight Ink": "Mực đêm",
  "Deep void + jade accents": "Nền tối sâu với điểm nhấn ngọc",
  "Mountain Mist": "Sương núi",
  "Ink wash + mist": "Mực loang và sương mờ",
  "Calligraphy": "Thư pháp",
  "Monochrome scroll style": "Phong cách cuộn giấy đơn sắc",
  "Sakura": "Sakura",
  "Light blossom palette": "Bảng màu hoa anh đào sáng",
  "Sakura Dark": "Sakura tối",
  "Deep rose dusk": "Hoàng hôn hồng đậm",
  "Eternal": "Vĩnh hằng",
  "Clean minimalist": "Tối giản tinh gọn",
  "Discord": "Discord",
  "Discord-inspired dark": "Tông tối lấy cảm hứng từ Discord",
  "Document": "Tài liệu",
  "Paper + slate": "Giấy và đá phiến",
  "Nyaa": "Nyaa",
  "Nyaa blue-green": "Xanh lam ngọc Nyaa",
  "UI in English": "Giao diện bằng tiếng Anh",
  "UI in Vietnamese": "Giao diện bằng tiếng Việt",
  "User Settings": "Cài đặt người dùng",
  "Open user physique settings": "Mở cài đặt thể trạng người dùng",
  "Used to auto-select gym progression tier from average set weight vs bodyweight percentage.": "Dùng để tự động chọn tầng lộ trình gym từ trung bình tạ mỗi set so với phần trăm cân nặng cơ thể.",
  "Gender": "Giới tính",
  "Male": "Nam",
  "Female": "Nữ",
  "Gender affects weight standard calculations for your tier": "Giới tính ảnh hưởng đến việc tính chuẩn tạ cho tầng của bạn",
  "Bodyweight (kg)": "Cân nặng cơ thể (kg)",
  "Sync with Check-In Weight": "Đồng bộ với cân nặng điểm danh",
  "Automatically updated from check-ins": "Tự động cập nhật từ điểm danh",
  "Loading check-in data...": "Đang tải dữ liệu điểm danh...",
  "e.g. 82.5": "ví dụ: 82.5",
  "Use Last Known Weight": "Dùng cân nặng gần nhất",
  "Last check-in:": "Điểm danh gần nhất:",
  "No check-in weight records found": "Không tìm thấy bản ghi cân nặng điểm danh",
  "Failed to load check-in data": "Không thể tải dữ liệu điểm danh",
};

const VI_TO_EN_MAP: Record<string, string> = Object.fromEntries(
  Object.entries(EN_TO_VI_MAP).map(([en, vi]) => [vi, en]),
);

export function translateEnglishToLanguage(englishText: string, _languageMode: LanguageMode): string {
  return englishText;
}

export function getLearningHintFromEnglish(_englishText: string, _languageMode: LanguageMode): string | null {
  return null;
}

export function translateLooseText(text: string, _languageMode: LanguageMode): string {
  return text;
}

export function reverseTranslateLooseText(text: string): string | null {
  return VI_TO_EN_MAP[text] ?? null;
}
